# 设置基础镜像为 python:3.13-alpine
FROM python:3.13-alpine

# 设置工作目录为 /app
WORKDIR /app

# 复制依赖文件
COPY requirements.txt .

# 安装依赖
RUN pip install --no-cache-dir -r requirements.txt

# 复制所有文件
COPY . .

# 启动容器
CMD ["python", "coffeemachine_sim.py"]




